ecommerce_site/accounts/urls.py
from django.urls import path, include
from . import views

app_name = "accounts"

urlpatterns = [
    path('register/', views.register, name='register'),
]

ecommerce_site/ecommerce_app/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "ecommerce_app"

urlpatterns = [
    path('', views.home, name='home'),
    path('home', views.home, name='home'),
    path('home/', views.home, name='home'),

    path('update_product/<int:id>', views.update_product, name='update_product'),
    path('delete_product/<int:pk>', views.delete_product, name='delete_product'),
    path('all_products/', views.all_products, name='all_products'),
    path('category_wise_products/<str:category>', views.category_wise_products, name='category_wise_products'),

    path('create_product/', views.create_product, name="create_product"),
    path('create_category/', views.create_category_popup, name="create_category"),
    path('category/ajax/get_category_id', views.get_category_id, name="get_category_id"),
    url(r'^category/(?P<pk>\d+)/edit', views.edit_category_popup, name="edit_category"),

    path('home/request_new_product/', views.request_new_product, name='request_new_product'),
    path('request_new_product/', views.request_new_product, name='request_new_product'),
    path('home/show_unseen_product_requests/', views.show_unseen_product_requests, name = 'show_unseen_product_requests'),
    path('show_unseen_product_requests/', views.show_unseen_product_requests, name = 'show_unseen_product_requests'),
    path('show_unseen_product_requests/mark_requests_as_read/', views.mark_requests_as_read, name = 'mark_requests_as_read'),
    path('home/show_unseen_product_requests/mark_requests_as_read/', views.mark_requests_as_read, name = 'mark_requests_as_read'),

    path('user_cart/', views.user_cart, name='user_cart'),
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

ecommerce_site/ecommerce_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('accounts.urls')),
    path('', include('ecommerce_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

ecommerce_site/templates/products/crud/all_products.html
{% extends 'base.html' %}
{% block title %}
<title>All Products</title>
{% endblock %}
{% block content %}
<br />
<br />
<br />
<h1 class="ml-4" style="font-family: 'Open Sans';">List of Products</h1>
<div class="border rounded p-4 m-4">
    <a href="{% url 'ecommerce_app:create_product' %}" class="btn btn-primary ml-2" role="button"> <i class="fa fa-plus"></i> Add New Product</a><br />
    <table class="table">
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Date</th>
            <th>Price</th>
            <th>Inventory</th>
            <th>Brand</th>
            <th>Vendor</th>
            <th>image</th>
            <th>category</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        {% if products %} {% for product in products %}
        <tr>
            <th>{{ product.id }}</th>
            <td>{{ product.name }}</td>
            <td>{{ product.arrival_date }}</td>
            <td>{{ product.price }}</td>
            <td>{{ product.inventory_count }}</td>
            <td>{{ product.brand }}</td>
            <td>{{ product.vendor }}</td>
            <td>
                <img src="{{ product.image.url }}" class="img-responsive" style="width: 50px; height: 50px;" />
            </td>
            <td>{{ product.category }}</td>
            <td>
                <a href="{% url 'ecommerce_app:update_product' product.id %}" name="update" class="submit btn btn-outline-success"> <i class="fa fa-edit"></i></a>
            </td>
            <td>
                <form method="post" action="{% url 'ecommerce_app:delete_product' product.pk %}">
                    {% csrf_token %}
                    <button class="submit btn btn-outline-danger"><i class="fa fa-trash"></i></button>
                </form>
            </td>
        </tr>
        {% endfor %} {% endif %}
    </table>
</div>
{% endblock %}

ecommerce_site/templates/products/crud/category_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <br />
    <br />
    <br />
    <h4>Enter Category</h4>
    <form method="POST" action="" enctype="multipart/form-data" novalidate id="author-form">
        {% csrf_token %}
        {{form|crispy }}
        <input class="btn btn-primary" type="submit" value="Submit" />
    </form>
</div>
{% endblock %}

ecommerce_site/templates/products/crud/product_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<div class="container">
    <br />
    <br />
    <br />
    <br />
    <h1>Add Product</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.name|as_crispy_field }}
        {{ form.arrival_date|as_crispy_field }}
        {{ form.price|as_crispy_field }}
        {{ form.inventory_count|as_crispy_field }}
        {{ form.brand|as_crispy_field }}
        {{ form.vendor|as_crispy_field }}
        {{ form.image|as_crispy_field }}
        {{ form.category|as_crispy_field }}

        <a class="btn btn-success" href="{% url 'ecommerce_app:create_category' %}" id="add_author" onclick="return showAddPopup(this);"> add category</a>
        <a class="btn btn-danger" id="edit_category" style="color: white;"> edit category</a><br />
        <br />
        <input class="btn btn-primary" type="submit" value="Submit" />
    </form>
</div>
{% endblock %}

ecommerce_site/templates/products/crud/search_product.html
{% extends 'base.html' %} {% block content %} <br />
<br />
<br />
<div class="container">
    <!--When User search for a product, products will display here.-->
    <div class="row">
        {% if filtered_product %} {% for product in filtered_product %}
        <div class="col-sm-3" style="height: 365px; background-color: whitesmoke; border: 6px solid white;">
            <img src="{{ product.image.url }}" alt="" class="img-fluid" />
            <center>
                <h3>{{ product.name }}</h3>
                <h4 style="color: red;">{{ product.price }}</h4>
            </center>
            <button style="width: 250px;" class="btn btn-danger">Add to Cart</button>
        </div>
        {% endfor %}
        {% else %}
        <div class="container">
            <div class="alert alert-info alert-dismissible">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <strong>Not Found!</strong> No similar Products found
            </div>
            Do you want to request for this product. Click
            <a href="{% url 'ecommerce_app:request_new_product' %}"> Here</a>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

ecommerce_site/templates/products/crud/update_product.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}

{% block title %}
<title>Update Product</title>
{% endblock %}
<br />
<br />
<br />
<div class="card ml-3" style="width: 45%; height: 30%;">
    <div class="card-body">
        <div class="container">
            <h2 style="font-family: 'Open Sans';">Update Product</h2>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %} {{ form|crispy }}
                <button name="edit" type="submit" class="btn btn-success ml-2"><i class="fa fa-edit"></i> Edit and Save</button>
                <a href="{% url 'ecommerce_app:all_products' %}" class="btn btn-danger" role="button"><i class="fa fa-times"></i> Cancel</a>
            </form>
        </div>
    </div>
</div>
<br />
{% endblock %}