ecommerce_site/accounts/urls.py
from django.urls import path, include
from . import views

app_name = "accounts"

urlpatterns = [
    path('register/', views.register, name='register'),
]

ecommerce_site/ecommerce_app/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "ecommerce_app"

urlpatterns = [
    path('', views.home, name='home'),
    path('home', views.home, name='home'),
    path('home/', views.home, name='home'),

    path('update_product/<int:id>', views.update_product, name='update_product'),
    path('delete_product/<int:pk>', views.delete_product, name='delete_product'),
    path('all_products/', views.all_products, name='all_products'),
    path('category_wise_products/<str:category>', views.category_wise_products, name='category_wise_products'),

    path('create_product/', views.create_product, name="create_product"),
    path('create_category/', views.create_category_popup, name="create_category"),
    path('category/ajax/get_category_id', views.get_category_id, name="get_category_id"),
    url(r'^category/(?P<pk>\d+)/edit', views.edit_category_popup, name="edit_category"),

    path('home/request_new_product/', views.request_new_product, name='request_new_product'),
    path('request_new_product/', views.request_new_product, name='request_new_product'),
    path('home/show_unseen_product_requests/', views.show_unseen_product_requests, name = 'show_unseen_product_requests'),
    path('show_unseen_product_requests/', views.show_unseen_product_requests, name = 'show_unseen_product_requests'),
    path('show_unseen_product_requests/mark_requests_as_read/', views.mark_requests_as_read, name = 'mark_requests_as_read'),
    path('home/show_unseen_product_requests/mark_requests_as_read/', views.mark_requests_as_read, name = 'mark_requests_as_read'),

    path('user_cart/', views.user_cart, name='user_cart'),
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

ecommerce_site/ecommerce_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('accounts.urls')),
    path('', include('ecommerce_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

ecommerce_site/ecommerce_app/models.py
from django.db import models


class ProductCategory(models.Model):
    category = models.CharField(max_length=100)

    def __str__(self):
        return self.category


class Product(models.Model):
    name = models.CharField(max_length=100)
    arrival_date = models.DateField()
    price = models.FloatField()
    inventory_count = models.IntegerField(default=0)
    brand = models.CharField(max_length=100)
    vendor = models.CharField(max_length=100)
    image = models.ImageField(upload_to='images/')
    category = models.ForeignKey(ProductCategory, on_delete = models.CASCADE)

    def __str__(self):
        return '{} {}'.format(self.name, self.category.category)

    def delete(self, *args, **kwargs):
        self.image.delete()
        super().delete(*args,**kwargs)

    @staticmethod
    def get_products_by_id(ids):
        return Product.objects.filter(id__in = ids)


class CustomerProductRequest(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    product_name = models.CharField(max_length=100)
    product_type = models.CharField(max_length=100)
    product_description = models.TextField()
    request_seen = models.BooleanField(default=False)

    def __str__(self):
        return '{} {} {}'.format(self.name, self.product_name, self.request_seen)

ecommerce_site/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}<title></title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/static/css/main.css?{% now "U" %}"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</head>
<body>
{% block script %}
<script type="text/javascript">
function showEditPopup(url) {
    var win = window.open(url, "Edit",
        'height=500,width=800,resizable=yes,scrollbars=yes');
    return false;
}
function showAddPopup(triggeringLink) {
    $("#display").text(triggeringLink)
    var name = triggeringLink.id.replace(/^add_/, '');
    href = triggeringLink.href;
    var win = window.open(href, name, 'height=500,width=800,resizable=yes,scrollbars=yes');
    win.focus();
    return false;
}
function closePopup(win, newID, newRepr, id) {
    $(id).append('<option value=' + newID + ' selected >' + newRepr + '</option>')
    win.close();
}

    $(document).ready(function(){
$("#edit_category").click(function(){
    category_name = $("#id_category option:selected").text();
	//var data = {"author_name":author_name};
    $.ajax({
        type : 'GET',
        url :  '/category/ajax/get_category_id',
        data : {
            "category_name":category_name
        },
        success : function(data){
        	var url = "/category/" + data['category_id'] + "/edit/";
        	showEditPopup(url);
        },
        error: function(data) {
          alert("Something Went Wrong");
        }
  	});
})
});
</script>
{% endblock %}

<nav class="navbar fixed-top navbar-expand-md navbar-dark bg-dark">
    <a href="{% url 'ecommerce_app:home' %}" class="navbar-brand">E-Shop</a>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="navbar-nav">
            <a href="{% url 'ecommerce_app:home' %}" class="nav-item nav-link {% ifequal request.path '/home/'%} active {% endifequal%}">
                <i class="fa fa-fw fa-home"></i> Home</a>

            {% if user.is_active and user.is_superuser %}
                <a href="{% url 'ecommerce_app:all_products' %}" class="nav-item nav-link
                    {% ifequal request.path '/all_products/'%} active {% endifequal%}">
                    <i class="fa fa-fw fa-product-hunt"></i> Products</a>
            {% endif %}
        </div>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link {% ifequal request.path '/user_cart/'%} active {% endifequal%}"
                   href="{% url 'ecommerce_app:user_cart' %}"><i class="fa fa-shopping-cart"> Cart</i>
                </a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">
                    <i class="fa fa-sign-out">Logout</i></a>
                </li>
            {% else %}
                <li class="nav-item"><a class="nav-link {% ifequal request.path '/accounts/login/'%} active {% endifequal%}" href="{% url 'login' %}">
                    <i class="fa fa-sign-in"> Login</i></a>
                </li>
                <li class="nav-item"><a class="nav-link {% ifequal request.path '/register/'%} active {% endifequal%}" href="{% url 'accounts:register' %}">
                    <i class="fa fa-sign-up"> Sign Up</i></a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>
{% block content %}
{% endblock %}
<br>
</body>

</html>

ecommerce_site/templates/index.html
{% extends 'base.html' %}
{% load product_cart_filters %}
{% load static %}

{% block title %}
    <title>Home</title>
{% endblock %}

{% block content %}
<div class="row" style="height: 100px; background-color: whitesmoke; margin-top: 50px;">
     <form method="post" class="form-inline ml-4">
         {% csrf_token %}
            <input name="product_input" type="text" style="width: 350px;" class="form-control mr-sm-1"
                   placeholder="Search Product">
            <button style="width: 100px;" type="submit" class="btn btn-success">Search</button>
     </form>
    {% if user.is_active and user.is_superuser %}
    <ul class="navbar-nav ml-auto mt-4">
        <li class="mr-4">
            <a href = "show_unseen_product_requests/" class="notification border-0">
                <i class="fa fa-envelope"></i>
                <span class="badge">{{ new_product_requests_count }}</span>
            </a>
        </li>
    </ul>
    {% endif %}
</div>
     {% if messages %}
         {% for message in messages %}
             <div  id="success-alert" class="alert alert-danger alert-dismissible" role="alert">{{ message }}</div>
         {% endfor %}
     {% endif %}
    <br>
    <!--Here unique categories will go here in tabs for home page-->
<div class="container">
<ul class="nav nav-pills">
<li class="nav-item">
{% if categories %}
    <a class="nav-link {% if request.resolver_match.view_name == 'ecommerce_app:home' %}active{% endif %}"
       href="{% url 'ecommerce_app:home' %}">All</a></li>
  {% for category in categories %}
        <li class="nav-item">
            <a class="nav-link"
               href="{% url 'ecommerce_app:category_wise_products' category %}">{{ category }}</a>
        </li>
    {% endfor %}
{% endif %}
</ul>
<br>

<!--Displaying all products, as well as products according to clicked tab-->
<h3 style="font-family: 'Times New Roman'; color: blue;">{{ category_heading }}</h3>
<div class="row">
    {% for product in products %}
        <div class='card' id="{{ product.id }}" style="padding: 0; border: 4px solid white; background-color: whitesmoke">
        <div class="card-body">
            <img src="{{ product.image.url }}"  alt = "" class="img-fluid" style="height: 230px;">
            <p class="text-center">{{ product.name }}</p>
            <p class="text-center text-danger">{{ product.price }}</p>
            <!-- product| is_product_in_cart:request.session.cart }}-->
        </div>
        <div class="footer">
           {% if product|is_product_in_cart:request.session.cart%}
             <div class="row no-gutters">
                <form method="post" class="col-2">
                    {% csrf_token %}
                    <input type="text" hidden name="product_id" value="{{ product.id }}">
                    <input type="text" hidden name="is_product_removed" value="True">
                    <input type="submit" value=" - " class="btn btn-block btn-success p-0">
                </form>
                <div class="text-center col">{{ product|product_count_in_cart:request.session.cart }} in cart</div>
                <form method="post" class="col-2">
                    {% csrf_token %}
                    <input type="text" hidden name="product_id" value="{{ product.id }}">
                    <input type="submit" value=" + " class="btn btn-block btn-success p-0">
                </form>
            </div>
            {% else %}
            <form method="post" action="/#{{product.id}}" class = 'btn-block'>
                {% csrf_token %}
                <input hidden name="product_id"  type="text" value="{{ product.id }}">
                <button class="btn btn-danger float-right">Add to Cart</button>
            </form>
            {% endif %}
        </div>
        </div>
    {% endfor %}
</div>
</div>
{% endblock %}